import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'
export default function Home({results}) {
 
  return (
    <div className="">
      <Head>
        <title>Hulu | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu-app.jpg" />
      </Head>       
        {/*  Header */}

          <Header/>
          <Banner/>

        {/* Navbar */}
      <Nav/>

  
        {/* Results */}
      <Results results = {results} />

      <Footer/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || 
  requests.fetchTrending.url }`
  ).then((res) => res.json()
  
  
  );
  


  return {
    props: {
      results: request.results,
    }
  }
}